#!/bin/bash

# Script skrevet en af anden gruppe

make clean &&
make &&
cd tests &&
make clean &&
make &&
cd .. &&
util/tfstool delete fyams.harddisk readwrite &&
util/tfstool write fyams.harddisk tests/readwrite readwrite &&
fyams-sim buenos initprog=[disk]readwrite
